wandb_version: 1

class:
  desc: null
  value: ConditionalMemoryAgent
model:
  desc: null
  value: mistralai/Mixtral-8x7B-Instruct-v0.1
label:
  desc: null
  value: t
date:
  desc: null
  value: '06110145'
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718070305
    t:
      1:
      - 5
      - 53
      - 55
      - 95
      - 105
      2:
      - 5
      - 53
      - 55
      - 95
      - 105
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
